[package]
name = "ende-derive"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.55", features = ["full"] }
quote = "1.0.35"
proc-macro2 = "1.0.79"
parse-display = "0.9.0"
proc-macro-crate = "3.1.0"