[package]
name = "ende-derive"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.55", features = ["full", "visit-mut"] }
quote = "1.0.35"
proc-macro2 = "1.0.79"

[features]
default = []
unstable = []